import json
import os
import sys
import yaml

from datetime import datetime, UTC

HISTORY_FILE  = os.path.join(os.path.dirname(__file__), '..', 'reports', 'test_history.json')
RULES_FILE    = os.path.join(os.path.dirname(__file__), '..', 'configs', 'promotion_rules.yaml')
PYTEST_REPORT = os.path.join(os.path.dirname(__file__), '..', 'reports', 'pytest-results.json')

# pytest-results.json will be generated by CI pipeline and result will get appended to test_history.json

def evaluate(pytest_report=PYTEST_REPORT) -> dict:
    """
    Read pytest's JSON report and check results against promotion_rules.yaml.

    In CI, this file is written by:
        pytest --json-report --json-report-file=reports/pytest-results.json

    Returns:
        passed     — True = promote, False = block
        pass_rate  — % of tests that passed
        total      — total tests run
        failed     — number of failures
        reasons    — list of human-readable block reasons (empty if passed)
    """
    with open(RULES_FILE) as f:
        rules = yaml.safe_load(f)

    with open(pytest_report) as f:
        report = json.load(f)

    summary  = report["summary"]
    total    = summary.get("total", 0)
    passed   = summary.get("passed", 0)
    failed   = total - passed
    pass_rate = passed / total if total > 0 else 0.0

    reasons = []
    if pass_rate < rules["min_pass_rate"]:
        reasons.append(
            f"Pass rate {pass_rate:.1%} is below minimum {rules['min_pass_rate']:.1%}"
        )

    return {
        "passed":    len(reasons) == 0,
        "pass_rate": round(pass_rate, 3),
        "total":     total,
        "failed":    failed,
        "reasons":   reasons,
    }


def append_to_history(gate_result: dict):
    """
    Append one row to test_history.json after every CI run so the
    Streamlit dashboard reflects real CI health over time.
    This func is called by CI after gate evaluation, regardless of pass/fail.
    """
    with open(HISTORY_FILE) as f:
        history = json.load(f)

    day = len(history) + 1
    row = {
        "day":                day,
        "date":               datetime.now(UTC).strftime("%Y-%m-%d"),
        "scenario":           "ci_run",
        "stage_reached":      "pytest",
        "target_version":     "ci",
        "production_version": "ci",
        "blocked_at":         None if gate_result["passed"] else "gate",
        "total":              gate_result["total"],
        "succeeded":          gate_result["total"] - gate_result["failed"],
        "failed":             gate_result["failed"],
        "pass_rate":          gate_result["pass_rate"],
        "rollback_triggered": not gate_result["passed"],
    }
    history.append(row)

    with open(HISTORY_FILE, 'w') as f:
        json.dump(history, f, indent=4)


if __name__ == "__main__":
    result = evaluate()
    status = "PASS" if result["passed"] else "BLOCK"
    print(f"Gate: {status} | pass_rate={result['pass_rate']:.1%} | failed={result['failed']}/{result['total']}")
    for reason in result["reasons"]:
        print(f"  REASON: {reason}")

    # record the result of this CI run
    append_to_history(result)
    print(f"Appended CI run row to {HISTORY_FILE}")

    # Exit 1, CI pipeline fails and PR is blocked
    if not result["passed"]:
        sys.exit(1)

