import json
import os
import sys
import yaml

from datetime import datetime, UTC

# Ensure project root is on sys.path so 'device_simulator' is importable
# when gates.py is run directly (e.g. python pipeline/gates.py).
# Also add device_simulator/ itself so fleet.py's internal bare imports resolve.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'device_simulator'))

from device_simulator import fleet

HISTORY_FILE  = os.path.join(os.path.dirname(__file__), '..', 'reports', 'test_history.json')
RULES_FILE    = os.path.join(os.path.dirname(__file__), '..', 'configs', 'promotion_rules.yaml')
PYTEST_REPORT = os.path.join(os.path.dirname(__file__), '..', 'reports', 'pytest-results.json')

# pytest-results.json will be generated by CI pipeline and result will get appended to test_history.json

def evaluate(pytest_report=PYTEST_REPORT) -> dict:
    """
    Read pytest's JSON report and check results against promotion_rules.yaml.

    In CI, this file is written by:
        pytest --json-report --json-report-file=reports/pytest-results.json

    Returns:
        passed     — True = promote, False = block
        pass_rate  — % of tests that passed
        total      — total tests run
        failed     — number of failures
        reasons    — list of human-readable block reasons (empty if passed)
    """
    with open(RULES_FILE) as f:
        rules = yaml.safe_load(f)

    with open(pytest_report) as f:
        report = json.load(f)

    summary  = report["summary"]
    total    = summary.get("total", 0)
    passed   = summary.get("passed", 0)
    failed   = total - passed
    pass_rate = passed / total if total > 0 else 0.0

    reasons = []
    if pass_rate < rules["min_pass_rate"]:
        reasons.append(
            f"Pass rate {pass_rate:.1%} is below minimum {rules['min_pass_rate']:.1%}"
        )

    return {
        "passed":    len(reasons) == 0,
        "pass_rate": round(pass_rate, 3),
        "total":     total,
        "failed":    failed,
        "reasons":   reasons,
    }


def _bump_version(version: str) -> str:
    """Increment the patch number: 1.0.249 → 1.0.250"""
    major, minor, patch = version.split(".")
    return f"{major}.{minor}.{int(patch) + 1}"


def append_to_history(gate_result: dict):
    """
    After pytest gate evaluation, simulate a staging rollout and append the
    result as a normal_release row to test_history.json.

    If pytest itself failed the gate (before any device touched), record a
    blocked row so the dashboard still reflects the CI run.

    Called after every CI run regardless of pass/fail.
    """
    with open(HISTORY_FILE) as f:
        history = json.load(f)

    day = len(history) + 1
    date_str = datetime.now(UTC).strftime("%Y-%m-%d")

    # Scan backward for the last row with a real semver target_version.
    # Old "ci_run" rows used "ci" as the version — skip those.
    last_target = "1.0.219"
    last_production = "1.0.219"
    for row in reversed(history):
        tv = row.get("target_version", "")
        if tv.count(".") == 2:
            last_target = tv
            last_production = row.get("production_version", last_production)
            break
    candidate_version = _bump_version(last_target)

    if not gate_result["passed"]:
        # pytest gate blocked — no device rollout happens, record it as blocked at gate
        row = {
            "day":                day,
            "date":               date_str,
            "scenario":           "normal_release",
            "stage_reached":      "gate",
            "target_version":     candidate_version,
            "production_version": last_production,
            "blocked_at":         "gate",
            "total":              gate_result["total"],
            "succeeded":          gate_result["total"] - gate_result["failed"],
            "failed":             gate_result["failed"],
            "pass_rate":          gate_result["pass_rate"],
            "rollback_triggered": True,
        }
    else:
        # pytest passed — simulate a staging rollout (low noise, CI environment)
        staging_results = fleet.rollout("staging", candidate_version, fail_probability=0.05)
        summary = fleet.health_summary(staging_results)
        row = {
            "day":                day,
            "date":               date_str,
            "scenario":           "normal_release",
            "stage_reached":      "staging",
            "target_version":     candidate_version,
            "production_version": last_production,
            "blocked_at":         "staging" if summary["rollback_triggered"] else "N/A",
            **summary,
        }

    history.append(row)
    with open(HISTORY_FILE, 'w') as f:
        json.dump(history, f, indent=4)


if __name__ == "__main__":
    result = evaluate()
    status = "PASS" if result["passed"] else "BLOCK"
    print(f"Gate: {status} | pass_rate={result['pass_rate']:.1%} | failed={result['failed']}/{result['total']}")
    for reason in result["reasons"]:
        print(f"  REASON: {reason}")

    # record the result of this CI run
    append_to_history(result)
    print(f"Appended CI run row to {HISTORY_FILE}")

    # Exit 1, CI pipeline fails and PR is blocked
    if not result["passed"]:
        sys.exit(1)

