import json
import pandas as pd
import os

TEST_HISTORY_PATH = os.path.join(os.path.dirname(__file__), '..', 'reports', 'test_history.json')
EVENTS_PATH       = os.path.join(os.path.dirname(__file__), '..', 'reports', 'events.json')

def load_history(path=TEST_HISTORY_PATH) -> pd.DataFrame:
    with open(path) as f:
        data = json.load(f)
    df = pd.DataFrame(data)
    df["date"] = pd.to_datetime(df["date"])
    return df

def load_events(path=EVENTS_PATH) -> pd.DataFrame:
    """Load the raw per-device event log generated by the device simulator."""
    if not os.path.exists(path):
        return pd.DataFrame()
    with open(path) as f:
        data = json.load(f)
    df = pd.DataFrame(data)
    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df

if __name__ == "__main__":
    df = load_history()
    print(df.head())