import json
import yaml
import os

PYTEST_SIM_HISTORY = os.path.join(os.path.dirname(__file__), '..', 'reports', 'test_run_history.json')
CONFIG_FILE = os.path.join(os.path.dirname(__file__), '..', 'configs', 'flake_config.yaml')
QUARANTINE_FILE = os.path.join(os.path.dirname(__file__), '..', 'configs', 'quarantined_tests.yaml')


def analyze() -> dict:
    """
    Read test_run_history.json and find tests that flip pass/fail
    more than the defined threshold within the rolling window.

    Returns:
        flaky       — list of test IDs flagged as flaky
        quarantined — list of test IDs written to quarantine file
        details     — dict of {test_id: {flips, last_n_results}}
    """
    with open(CONFIG_FILE) as f:
        config = yaml.safe_load(f)

    with open(PYTEST_SIM_HISTORY) as f:
        history = json.load(f)  # list of {test_id, run, passed} generated by seed_flake_history.py

    window    = config["window_size"]
    threshold = config["flip_threshold"]

    # Group results by test_id, keep only the last `window` runs each
    by_test = {}
    for entry in history:
        tid = entry["test_id"]
        by_test.setdefault(tid, []).append(entry["passed"])
    for tid in by_test:
        by_test[tid] = by_test[tid][-window:]

    # Count flips (consecutive result changes) per test
    flaky   = []
    details = {}
    for tid, results in by_test.items():
        flips = sum(1 for i in range(1, len(results)) if results[i] != results[i - 1])
        details[tid] = {"flips": flips, "last_runs": results}
        if flips > threshold:
            flaky.append(tid)

    # Write flaky tests to quarantine file if auto_quarantine is on
    quarantined = []
    if config["auto_quarantine"] and flaky:
        existing = _load_quarantine()
        newly_quarantined = [t for t in flaky if t not in existing]
        if newly_quarantined:
            existing.extend(newly_quarantined)
            with open(QUARANTINE_FILE, 'w') as f:
                yaml.dump({"quarantined_tests": existing}, f)
            quarantined = newly_quarantined

    return {"flaky": flaky, "quarantined": quarantined, "details": details}


def _load_quarantine() -> list:
    if not os.path.exists(QUARANTINE_FILE):
        return []
    with open(QUARANTINE_FILE) as f:
        data = yaml.safe_load(f) or {}
    return data.get("quarantined_tests", [])


if __name__ == "__main__":
    result = analyze()
    print(f"Flaky tests found: {len(result['flaky'])}")
    for tid in result["flaky"]:
        d = result["details"][tid]
        print(f"  {tid}: {d['flips']} flips in last {len(d['last_runs'])} runs")
    if result["quarantined"]:
        print(f"Newly quarantined: {result['quarantined']}")
